# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auhor',
            new_name='Author',
        ),
    ]
