# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20180220_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books_author',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
    ]
