# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books_author',
            new_name='books',
        ),
    ]
