# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='placeholder for a description about the dojo'),
            preserve_default=False,
        ),
    ]
