# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0002_auto_20180302_0257'),
        ('ajaxNotes', '0002_auto_20180301_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to='loginReg.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='left',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='note',
            name='top',
            field=models.IntegerField(default=100),
        ),
    ]
